language: c++
install: 
- cd $TRAVIS_BUILD_DIR/examples/pxscene2d/external
- ./build.sh 1&>/dev/null
- cd $TRAVIS_BUILD_DIR

script:  $TRAVIS_BUILD_DIR/build_pxscene.sh
- make -f Makefile.glut
- cd $TRAVIS_BUILD_DIR/examples/pxscene2d/src
- make pxscene
- cd $TRAVIS_BUILD_DIR
