matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
    osx_image: xcode8.1
language: c++
install:
- mkdir $TRAVIS_BUILD_DIR/logs
- mkdir $TRAVIS_BUILD_DIR/logs/codecoverage
- touch $TRAVIS_BUILD_DIR/logs/build_logs
- touch $TRAVIS_BUILD_DIR/logs/run_logs;
- BUILDLOGS=$TRAVIS_BUILD_DIR/logs/build_logs
- touch $TRAVIS_BUILD_DIR/logs/pxcheck_logs;
- cd $TRAVIS_BUILD_DIR
- echo "***************************** Building externals ****" > $BUILDLOGS
- cd $TRAVIS_BUILD_DIR/examples/pxScene2d/external
- ./build.sh>>$BUILDLOGS
before_script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DISPLAY=:99.0; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh -e /etc/init.d/xvfb start; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sleep 3; fi
- ccache -s
script:
- cd $TRAVIS_BUILD_DIR
- sh build_px.sh "build_$TRAVIS_OS_NAME.sh" "testrunner_$TRAVIS_OS_NAME.sh" "code_coverage_$TRAVIS_OS_NAME.sh"
  "unittests_$TRAVIS_OS_NAME.sh" "pxleakcheck_$TRAVIS_OS_NAME.sh"
- cd $TRAVIS_BUILD_DIR
- coveralls --build-root $TRAVIS_BUILD_DIR --no-gcov --lcov-file tracefile
- genhtml -o $TRAVIS_BUILD_DIR/logs/codecoverage tracefile > coveralls_trace
- TRAVIS_MESSAGE="code coverage for $TRAVIS_OS_NAME is `grep \"lines...\" coveralls_trace|awk '{print $2}'`"
- sh memleakdetector_$TRAVIS_OS_NAME.sh
addons:
  ssh_known_hosts: 96.118.6.151
after_script:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then cd $TRAVIS_BUILD_DIR; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then tar -cvzf logs.tgz logs/* ; fi
- ccache -s
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then cd $TRAVIS_BUILD_DIR; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./deploy.sh 96.118.6.151 logs.tgz; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then rm -rf /tmp/pxscene-build.pem; fi
before_install:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then openssl aes-256-cbc -K $encrypted_8b763c087de9_key -iv $encrypted_8b763c087de9_iv  -in pxscene-build.pem.enc -out /tmp/pxscene-build.pem -d; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get update; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get install git
  libglew-dev freeglut3 freeglut3-dev libgcrypt11-dev zlib1g-dev g++ libssl-dev nasm
  autoconf valgrind libyaml-dev lcov; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ];  then brew update; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ];  then brew install gcovr; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ];  then brew install lcov; fi
- pip install cpp-coveralls
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install --HEAD ccache; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then ls -al $HOME/.ccache; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/opt/ccache/libexec:$PATH; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then eval "$(ssh-agent -s)"; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then  chmod 600 /tmp/pxscene-build.pem; fi
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then  ssh-add /tmp/pxscene-build.pem; fi
notifications:
  slack:
    secure: gQ7GjheuN4j98co71p1gO0QaIAX3xHnDE2JRTT5UopsPbhczBC3A6RlVhXBrIc9mDyt2AO/pTBOl68BGtwtb4NVhZo2fqCcoq4wk2U2bAH3OnQu5KE9fJxm1KdJi0WiFVy1pURQql1fUH800YqF1LOWbc9m8aexgcvtD6ghDFLCDStgqfNgRzSEbZ8YBP98FjkEHj/jjeqwdUaH0Aezv0n82Laev99KDveCTVMoKXcbyfBQK0ty3OFAg6nBrMWPx0RVDVOVFPjjXDFgC5UfS9FLA57bxRDVmDr8SMnS/7m26YH0jnqY4oS1QnEmrdUtp6UWNex8D88KCt+wXoOpd6Ca1DVHNnaFuotEVpJ8B3WEG3uiK6xvacpkMrtEuoswUIbOv8E1VdfF3eOSmSAneb09Nbs15U8yiBfNq4PLE8TYc22or5jDsksTyGgmOgE1m8teH4DQz+k5qhMihd9f88CqaWzkjNgucavr/QzXG16xt13unMmMD0/bzA7wDU3hprne5hycR0LDxFRlL5z5xdv4w9yseuFTYBRcQ5Lk9zA6gJUMCGcbCtfA2rYQS7lOul575EMX7SfagHMmn663QY3tzm+vsxF93Dib+xfsAI3xSxSKGeBNZ5H9MxUPNUcu1yxhDZIZX8HujsDVLfIm/VK9OS2ultBTYeKizlyPBBsM=
cache: ccache
