language: c++
sudo: required
dist: trusty
before_install: sudo apt-get install git libglew-dev freeglut3 freeglut3-dev libgcrypt11-dev zlib1g-dev g++ libssl-dev nasm autoconf
install: 
- cd $TRAVIS_BUILD_DIR/examples/pxScene2d/external
- ./build.sh>a.txt
- cd $TRAVIS_BUILD_DIR
script:
- make -f Makefile.glut
- cd $TRAVIS_BUILD_DIR/examples/pxscene2d/src
- make pxscene
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key: "308f96446629ddd00eef45c106287826b20f36c1"
  file: "$TRAVIS_BUILD_DIR/examples/pxScene2d/external/a.txt" 
  skip_cleanup: true
  on:
    tags: true
